#pragma once
#include <stdio.h>
#include <tchar.h>
#include <stdlib.h>
#include <iostream>
#include <string> 
#include <locale.h>
#include <sstream>
#include <algorithm>
#include <iomanip>
#include <stack>
#include <fstream>